personality = "pragmatic"

[marketplaces.openai-bundled]
last_updated = "2026-06-09T18:58:35Z"
source_type = "local"
source = "/Users/Niklas.Kappel/.codex/.tmp/bundled-marketplaces/openai-bundled"

[plugins."sites@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Users/Niklas.Kappel/Applications/Codex.app/Contents/Resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/Users/Niklas.Kappel/Applications/Codex.app/Contents/Resources/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/Niklas.Kappel/.codex"
CODEX_HOME = "/Users/Niklas.Kappel/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "2de792ebdf729e85542c94275f6654821dddce546d9c7374c915f2297529e313"
BROWSER_USE_AVAILABLE_BACKENDS = "iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.602.40724"
CODEX_CLI_PATH = "/Users/Niklas.Kappel/Applications/Codex.app/Contents/Resources/codex"

