# See: https://matthiasportzel.com/brewfile/
# Sync using: `brew update && brew bundle install --cleanup --file=~/.config/Brewfile && brew upgrade`

brew "fd"
brew "fish"
brew "htop"
brew "neovim"
brew "node"
brew "ripgrep"
brew "stow"
brew "tlrc"
brew "tree"
brew "uv"
brew "wget"

cask "alt-tab"
cask "bitwarden"
cask "firefox"
cask "font-dejavu-sans-mono-nerd-font"
cask "gpt4all"  # requires manual install
cask "hyperkey"
cask "iterm2"
cask "linearmouse"
cask "middleclick"
cask "rectangle"
cask "visual-studio-code"

# The packages below are not managed by brew.
# cask "displaylink"  # requires sudo
