brew "bat"
brew "fd"
brew "fish"
brew "fnm"
brew "fzf"
brew "htop"
brew "neovim"
brew "ripgrep"
brew "stow"
brew "tlrc"
brew "tree"
brew "tree-sitter-cli"
brew "uv"
brew "wget"
brew "yarn"

cask "bitwarden"
cask "firefox"
cask "ghostty"
cask "visual-studio-code"

# Mac
cask "alt-tab"
cask "appcleaner"
cask "hiddenbar"
cask "hyperkey"
cask "linearmouse"
cask "middleclick"
cask "rectangle"

# Documents
brew "ghostscript"
brew "imagemagick"
brew "texlab"
brew "typst"
cask "skim"
cask "zotero"

# AI
brew "anomalyco/tap/opencode"
cask "claude"
cask "claude-code"
cask "codex"
cask "codex-app"

# Cloud
tap "hashicorp/tap"
brew "hashicorp/tap/terraform"

# Azure
brew "azure-cli"
tap "azure/functions"
brew "azure/functions/azure-functions-core-tools@4"

# The following packages require sudo and are installed via Iru instead.
# cask "citrix-workspace"
# cask "docker-desktop"
